name: ðŸ”„ Push Translations to Transifex

on:
  workflow_dispatch:
  push:
    branches: [$default-branch]

jobs:
  push-translations:
    uses: openmrs/openmrs-contrib-gha-workflows/.github/workflows/tx-push.yml@main
    secrets:
      TRANSIFEX_TOKEN: ${{ secrets.TRANSIFEX_TOKEN }}
