language: node_js
node_js:
  - node
script:
  - npm test
  - npm run lint
  - npm run build
  - npm run build-storybook -- --quiet
  - echo "Folder name in Digital Ocean Spaces - $TRAVIS_COMMIT"
  - mkdir -p dist/@openmrs/esm-styleguide/$TRAVIS_COMMIT
  - mv dist/*.* dist/@openmrs/esm-styleguide/$TRAVIS_COMMIT/
deploy:
  - provider: s3
    access_key_id: "$DIGITAL_OCEAN_SPACES_KEY_ID"
    secret_access_key: "$DIGITAL_OCEAN_SPACES_ACCESS_KEY"
    bucket: "$DIGITAL_OCEAN_SPACES_BUCKET"
    endpoint: "$DIGITAL_OCEAN_SPACES_ENDPOINT"
    cache-control: "max-age=31536000"
    local_dir: dist
    skip_cleanup: true
    acl: public_read
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
    local_dir: storybook-static
    fqdn: styleguide.openmrs.org
    on:
      branch: master
after_deploy:
  - echo "Updating import map to point to new version of @openmrs/esm-styleguide"
  - statuscode=$(curl --output /dev/null --write-out %{http_code} -u $DEPLOYER_USERNAME:$DEPLOYER_PASSWORD -d '{ "service":"@openmrs/esm-styleguide","url":"https://spa-modules.nyc3.digitaloceanspaces.com/@openmrs/esm-styleguide/'$TRAVIS_COMMIT'/openmrs-esm-styleguide.js" }' -X PATCH $DEPLOYER_HOST/services\?env=prod -H "Accept:application/json" -H "Content-Type:application/json")
  - curlexitcode=$?
  - statuscode=${statuscode:--1} # default to -1
  - if [ "$curlexitcode" -ne 0 ]; then echo "Nonzero exit code from curl --> ${curlexitcode}"; fi
  - echo "Deployment Status Code --> ${statuscode}"
  - if [ "$statuscode" -ne 200 ]; then travis_terminate "$statuscode"; fi
